image: Visual Studio 2015

version: 0.11.4

branches:
  only:
    - master
    - release

max_jobs: 4

environment:
  OKJTVERSION: 0.11.4
  matrix:
  - TARGET_ARCH: x64
    QT: C:\Qt\5.10.1\msvc2015_64
    PLATFORM: amd64
    COMPILER: msvc
    VSVER: 14
    LONGARCH: x86_64
    BITS: 64bit
  - TARGET_ARCH: x86
    QT: C:\Qt\5.10.1\msvc2015
    PLATFORM: x86
    COMPILER: msvc
    VSVER: 14
    LONGARCH: x86
    BITS: 32bit

clone_depth: 1

init:
  - set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%

clone_folder: c:\projects\openkj

install:
  - ps: |
      Write-Host "Getting 7z.exe..." -ForegroundColor Cyan
      $exePath = "$($env:USERPROFILE)\7z.exe"
      $url = "https://storage.googleapis.com/okj-installer-deps/7z.exe"
      Write-Host "Downloading..."
      (New-Object Net.WebClient).DownloadFile($url, $exePath)
      Write-Host "Done." -ForegroundColor Green
build_script:
  - call "appveyor/build_windows.cmd"

artifacts:
  - path: OpenKJ-Tools-$(OKJTVERSION)-$(BITS)-setup.exe
    name: installer

deploy:
  provider: FTP
  protocol: sftp
  host: openkj.org
  username: $(deploy_user)
  password: $(deploy_pass)
  folder: $(APPVEYOR_REPO_BRANCH) 
  artifact: installer
