image: Visual Studio 2015

version: 1.0.10

branches:
  only:
    - master
    - release

max_jobs: 4

environment:
  OKJTVERSION: 1.0.10
  matrix:
  - TARGET_ARCH: x64
    QT: C:\Qt\5.10.1\msvc2015_64
    PLATFORM: amd64
    COMPILER: msvc
    VSVER: 14
    LONGARCH: x86_64
    BITS: 64bit
  - TARGET_ARCH: x86
    QT: C:\Qt\5.10.1\msvc2015
    PLATFORM: x86
    COMPILER: msvc
    VSVER: 14
    LONGARCH: x86
    BITS: 32bit

clone_depth: 1

init:
  - set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%

clone_folder: c:\projects\openkj

install:
  - ps: |
      Write-Host "Installing gsutil for gcloud storage deployment"
      $zipPath = "$($env:APPVEYOR_BUILD_FOLDER)\gsutil.zip"
      (New-Object Net.WebClient).DownloadFile('https://pub.storage.googleapis.com/gsutil.zip', $zipPath)
      7z x $zipPath -y
      $bytes = [System.Convert]::FromBase64String($env:boto)
      [System.IO.File]::WriteAllBytes("$env:USERPROFILE\.boto", $bytes)
  - ps: |
      Write-Host "Getting deps..." -ForegroundColor Cyan
      $exePath = "$($env:APPVEYOR_BUILD_FOLDER)/7z.exe"
      $dllPath = "$($env:APPVEYOR_BUILD_FOLDER)/7z.dll"
      $m3gPath = "$($env:APPVEYOR_BUILD_FOLDER)/mp3gain.exe"
      $url = "https://storage.googleapis.com/okj-installer-deps/7z.exe"
      $urldll = "https://storage.googleapis.com/okj-installer-deps/7z.dll"
      $urlm3g = "https://storage.googleapis.com/okj-installer-deps/mp3gain.exe"
      Write-Host "Downloading..."
      (New-Object Net.WebClient).DownloadFile($url, $exePath)
      (New-Object Net.WebClient).DownloadFile($urldll, $dllPath)
      (New-Object Net.WebClient).DownloadFile($urlm3g, $m3gPath)
      Write-Host "Done." -ForegroundColor Green
build_script:
  - call "appveyor/build_windows.cmd"

artifacts:
  - path: OpenKJ-Tools-$(OKJTVERSION)-$(BITS)-setup.exe
    name: installer

    #deploy:
    #  provider: FTP
    #  protocol: sftp
    #  host: openkj.org
    #  username: $(deploy_user)
    #  password: $(deploy_pass)
    #  folder: $(APPVEYOR_REPO_BRANCH) 
    #  artifact: installer
    #
deploy_script:
# Upload all zip files from artifacts. 
# You upload by simple using local paths, but it is better to do this with $artifacts as you are in 100% sync with artifacts
# Or is simple do `- gsutil\gsutil cp <local_file_path> gs://my-test-bucket (thus avoiding NativeCommandError in build log)
  - ps: $artifacts.values | ForEach-Object {.\gsutil\gsutil cp $_.path gs://openkj-tools/windows/$($env:APPVEYOR_REPO_BRANCH)}

