Document: openkjtools
Title: Debian openkjtools Manual
Author: <insert document author here>
Abstract: This manual describes what openkjtools is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openkjtools/openkjtools.sgml.gz

Format: postscript
Files: /usr/share/doc/openkjtools/openkjtools.ps.gz

Format: text
Files: /usr/share/doc/openkjtools/openkjtools.text.gz

Format: HTML
Index: /usr/share/doc/openkjtools/html/index.html
Files: /usr/share/doc/openkjtools/html/*.html
